@echo off
echo Starting AI BI Agent...

echo Starting FastAPI Backend...
start cmd /k "cd backend && venv\Scripts\activate && python main.py"

echo Starting React Frontend...
start cmd /k "cd frontend && npm run dev"

echo Both servers are starting...
