@echo off
echo Starting AI BI Agent...

echo Starting FastAPI Backend...
start cmd /k "cd api && venv\Scripts\activate && uvicorn index:app --host 0.0.0.0 --port 8000 --reload"

echo Starting React Frontend...
start cmd /k "npm run dev"

echo Both servers are starting...
